# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "heavy02011"
repo_name: "LLM-arxiv-daily"
show_authors: True
show_links: True
max_results: 20

publish_readme: True
publish_gitpage: True

# file paths
json_readme_path: './docs/ro-arxiv-daily.json'
json_gitpage_path: './docs/ro-arxiv-daily-web.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'

# keywords to search
keywords:
    "RAG":
        filters: ["Retrieval Augmented Generation", "RAG", "RAG Evaluation", "RAG Benchmark", "RAG Agent"]
    "Large Language Model":
        filters: ["LLM", "Language Model","Transformer", "BERT", "GPT", "Pre-training", "Fine-tuning", "Visual Language", "Prompt Learning", "Foundation Model", "agents"]
    "Construction":
        filters: ["Construction", "Design", "BIM", "robots in construction", "cost optimization"]
